### ISSUE TITLE
User can select a music genre

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/ajax-project#1]
## ⚙️ Feature
User can select a music genre

## 📐 Functionality
User will select a genre based on a set of provided genres that will pull songs of that genre from Spotify API to help build their custom playlist

### Desktop
![Welcome Page (Pre-Login)](https://user-images.githubusercontent.com/90408240/154202733-e6991297-4897-4dc1-9ecb-b4ec628447c9.png)
![Welcome Page (Post-Login)](https://user-images.githubusercontent.com/90408240/154202729-558db6e8-5987-4c28-b0b0-44c0c472f617.png)
![Select A Genre](https://user-images.githubusercontent.com/90408240/154202726-f6f753af-ef4d-43b8-bb0c-ce1911a77ae4.png)

### Mobile
![Welcome Page (Pre-Login)](https://user-images.githubusercontent.com/90408240/154202937-49c1ecfb-a867-431f-a656-b663d4c8e227.png)
![Welcome Page (Post-Login)](https://user-images.githubusercontent.com/90408240/154202944-d357c2a9-685f-4d07-9541-dba54c66cb46.png)
![Select A Genre](https://user-images.githubusercontent.com/90408240/154202949-40e2d3de-9bb9-4f43-9ed3-3ca8b5e60753.png)

## ✅ Task List
- **All Pages**
   - [x] Create HMTL Skeleton for the Pre-Login and style in CSS for both desktop and mobile
   - [x] Create HMTL Skeleton for the Post-Login Page and style in CSS for both desktop and mobile 
   - [x] Create HTML Skeleton for the Select a Genre Page and style in CSS for desktop 
   - [x] Create HTML Skeleton for the Select a Genre Page and style in CSS for mobile
   - [x] Make sure that click targets are either `<a>` or `<button>` elements.
   - [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Pre-login Welcome Page**
   - [x] Sign in with Spotify button: click triggers the code for asking for oAuth verification (includes a sign in request on that page if you are not yet sign in on your browser) 
   - [x] Ensure the oAuth Client ID & Client Secret from Spotify Developer portal is hardcoded 
   - [x] When user agrees, redirect URI to the `Post-Login Welcome Page`
- **Post-login Welcome Page**
    - [x] "You are signed in" copy should be dynamic to the user's Spotify name 
    - [x] "Click here to sign in to Spotify" should take you back to the `Pre-Login Welcome page`
    - [x] "Create Playlist button" should take you to the `Select a Genre Page`
- **Select Genre Page** 
    - [x] When user clicks a genre button, it highlights to the select color and the data is saved in the data object in local storage
    - [x] If the user clicks a different button, the previously selected button will unhighlight & the new one will be highlighted with the select color & the new one's data will be stored in the data object in local storage
    - [x] Only allow the user to have 1 selection at a time (create a rule that will automatically unselect any other selected items)
    - [x] User clicks back arrow to be taken to the previous page 
    - [x] If user does not select a genre, stop the page from loading and create pop up window that says that they must select at least 1 option
    - [x] If user hovers over back arrow or checkmark, enlarge the images 
- **Playlist Algorithm Work**
    - [x] Use `Get Category Playlist` from Spotify API to pull a list of top playlists based on the selected Category and save this to a variable
    - [x] Push the top 20 Playlists from that category into the data and save to local storage
    - [x] Use a for loop to find the IDs of the playlists in the list and save to a variable in a list
    - [x] Use `Get Playlist Items` from Spotify API and use IDs that are stored in the list to pull the tracks data and save to another variable & in local storage
    - [x] Create a track ID list and save it to local storage
    - [x] Couple the track ID list in groups of 100 IDs at a time and save to local storage (will be used for later feature)
- **Clean Up**
  - [x] Clean up data.js and main.js so all local storage items live in data object
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
