### ISSUE TITLE
Refactor: Hide all api keys

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/ajax-project#13]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.
- [x] Explore how to change the project and hide api keys for all front end code
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
