### ISSUE TITLE
User can select a workout mode

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/ajax-project#3]
## ⚙️ Feature
User can select a workout mode

## 📐 Functionality
User will select a workout mode based on a set of provided modes based around a combination of energy, tempo, and danceability to help build their custom playlist

## 🖼️ Wireframes
![Select A Workout Mode](https://user-images.githubusercontent.com/90408240/155633606-0a744a90-acbf-494a-8314-3684bc35d6f5.png)
![Select A Workout Mode](https://user-images.githubusercontent.com/90408240/155633615-54fdaf19-a115-4230-b6fd-31bfe87f811f.png)

## ✅ Task List
- **Select Genre Page** 
   - [x] When user clicks the checkmark, trigger API pull `Get Tracks' Audio Features` based on the information already pulled from the previous feature
   - [x] When user clicks the checkmark, navigate to the `Workout Mode` Page
- **Workout Mode Page**
   - [x] Create HMTL Skeleton for the `Workout Mode` Page and style in CSS for both desktop and mobile
   - [x] When user clicks a workout mode button, it highlights to the select color and the data is saved in the data object in local storage
   - [x] If the user clicks a different button, the previously selected button will unhighlight & the new one will be highlighted with the select color & the new one's data will be stored in the data object in local storage
   - [x] Only allow the user to have 1 selection at a time (create a rule that will automatically unselect any other selected items)
   - [x] User clicks back arrow to be taken to the previous page 
   - [x] If user does not select a workout mode, stop the page from loading and create pop up window that says that they must select at least 1 option
    - [x] When user clicks the checkmark, ensure the workout mode data is saved in local storage
- **Playlist Algorithm Work**
    - [x] Fix data collection from API calls up to this point
    - [x] Get rid of tracks that are longer than 3.6 minutes or shorter than 1 minute and save to data.FilteredData in local storage
    - [x] Sort the tracks by a customValue which is a weighted combination of energy, tempo, and danceability
- **Clean Up**
  - [x] Fix all errors so app works if cache is cleared
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
