### ISSUE TITLE
User can select a workout duration

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/ajax-project#4]
## ⚙️ Feature
User can select a workout duration

## 📐 Functionality
User will select a workout duration based on a set of provided durations in minutes that will correspond to the approximate playlist length in minutes to be created.

## 🖼️ Wireframes
![Select A Duration](https://user-images.githubusercontent.com/90408240/156903001-b8742a19-3c84-42d0-a93e-681fe6b18c71.png)
![Select A Duration](https://user-images.githubusercontent.com/90408240/156903005-6ff226ae-a2d7-49e5-9124-50b13946d247.png)

## ✅ Task List
- **Workout Mode Page**
   - [x] When user clicks the checkmark, navigate to the `Select Duration` Page
- **Select Duration Page** 
   - [x] Create HTML skeleton for the `Select Duration` Page and style in CSS for both desktop and mobile
   - [x] When user clicks a duration button, it highlights to the select color and the data is saved in the data object in local storage
   - [x] If the user clicks a different button, the previously selected button will unhighlight & the new one will be highlighted with the select color & the new one's data will be stored in the data object in local storage
   - [x] Only allow the user to have 1 selection at a time (create a rule that will automatically unselect any other selected items)
   - [x] When user clicks the checkmark, trigger the algorithm that builds custom list based on duration and workout mode preferences
   - [x] When user clicks the back arrow, direct to the `Workout Mode` Page
- **Playlist Algorithm Work**
    - [x] Create createPlayListIDList function that checks duration and pulls out songs at "random" from the particular parts of the data.FilteredData.audioFeaturesMasterList with an if statement for Ramp Up workout mode that pulls corresponding track IDs and saves to data.playlistTrackDs in local storage
    - [x] Add an if statement for Hardcore workout mode that pulls corresponding track IDs and saves to data.playlistTrackDs in local storage
    - [x]  Add an if statement for Chill workout mode that pulls corresponding track IDs and saves to data.playlistTrackDs in local storage
    - [x]  Add an if statement for Ramp Up & Down workout mode that pulls corresponding track IDs and saves to data.playlistTrackDs in local storage
    - [x] Call Spotify API for `Get Tracks` using the data.playlistTrackDs and save the info in data.playlistInfoList and artist, trackNames into data.playlistSongList in local storage
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
