### ISSUE TITLE
User can preview the song list

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/ajax-project#5]
## ⚙️ Feature
User can preview the song list

## 📐 Functionality
User can see the song list before deciding to create the playlist.

## 🖼️ Wireframes
![Mix It](https://user-images.githubusercontent.com/90408240/156903157-d031df6c-d22d-4027-bc7c-3b270197b44e.png)
![Mix It](https://user-images.githubusercontent.com/90408240/156903159-e39038e0-5663-47f1-a169-213ffac9d44f.png)

## ✅ Task List
- **Select Duration Page**
   - [x] When user clicks the checkmark, navigate to the `Mix It` Page
- **Mix It Page**
   - [x] Create HMTL Skeleton for the `Mix It` Page and style in CSS for both desktop and mobile
   - [x] Ensure song list appears on the page according to all previous selections 
   - [x] When user clicks the back arrow, navigate back to `Duration` Page
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
