### ISSUE TITLE
User can name the playlist

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/ajax-project#6]
## ⚙️ Feature
User can name the playlist

## 📐 Functionality
User will be able to name the playlist before uploading it to their Spotify account. 

## 🖼️ Wireframes
![Upload to Spotify](https://user-images.githubusercontent.com/90408240/156903290-575413bb-357f-4828-9476-1ac9431231e9.png)
![Upload to Spotify](https://user-images.githubusercontent.com/90408240/156903291-59d0d777-ae42-48fa-a676-486518478d1c.png)

![Upload to Spotify (Modal)](https://user-images.githubusercontent.com/90408240/156903372-418c8e8c-9f27-4178-af30-e7ab1b330a79.png)
![Upload to Spotify (Modal)](https://user-images.githubusercontent.com/90408240/156903374-0c32412f-103d-47df-94b1-bc0f6c426af6.png)
## ✅ Task List
- **Mix It Page** 
   - [x] When user clicks the Create Playlist button, navigate to the `Name Playlist` Page
- **Name Playlist Page**
   - [x] Create HMTL Skeleton for the `Name Playlist` Page and style in CSS for both desktop and mobile 
   - [x] Create the HTML Skeleton for the modal pop-up and style in CSS for both desktop and mobile
   - [x] Ensure that the user is prompted with the modal pop-up when clicking the Upload to Spotify button
   - [x] Ensure when the user clicks the No, cancel button, the modal disappears and the user remains on the `Name Playlist` Page 
   - [x] Ensure when the user clicks the back arrow, redirected to the `Name Playlist` Page
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
