### ISSUE TITLE
User can upload the playlist to their Spotify account

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/ajax-project#7]
## ⚙️ Feature
User can upload the playlist to their Spotify account

## 📐 Functionality
Once the user confirms on the modal from the `Name Playlist` Page, a new playlist is created in their Spotify account and they have the option of viewing it in Spotify. 

## 🖼️ Wireframes
![Success Page](https://user-images.githubusercontent.com/90408240/156903445-4480f28f-2dfb-470a-876e-84da66e7a1e6.png)
![Success Page](https://user-images.githubusercontent.com/90408240/156903453-c27dbd1d-8046-43fb-82a1-ffcfcd9360e4.png)

## ✅ Task List
- **Name Playlist Page** 
   - [x] When user clicks the Yes, Upload button, ensure `Create Playlist` API call is made with the list of song IDs previously previewed 
   - [x] When user clicks the Yes, Upload button, navigate to the `Success` Page  
   - [x] When user clicks the Yes, Upload button, ensure the playlist name is saved in data.playlistName
- **Success Page** 
   - [x] Create HMTL Skeleton for the `Success` Page and style in CSS for both desktop and mobile
   - [x] When user clicks the open in Spotify button, ensure the user is redirected to their new Spotify playlist in the Spotify app
   - [x] When the user clicks the Create Another Playlist button, ensure the user is redirected to the `Create Playlist` Page
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
